// These type definitions have been generated by https://app.quicktype.io/ by providing the JSON response from the API

export type MovieAsSearchResult = {
  score: number;
  show: Show;
};

export type Show = {
  id: number;
  url: string;
  name: string;
  type: Type;
  language: Language;
  genres: string[];
  status: Status;
  runtime: number | null;
  averageRuntime: number | null;
  premiered: Date;
  ended: Date | null;
  officialSite: null | string;
  schedule: Schedule;
  rating: Rating;
  weight: number;
  network: Network | null;
  webChannel: Network | null;
  dvdCountry: null;
  externals: Externals;
  image: Image;
  summary: null | string;
  updated: number;
  _links: Links;
};

export type Links = {
  self: Self;
  previousepisode: Previousepisode;
};

export type Previousepisode = {
  href: string;
  name: string;
};

export type Self = {
  href: string;
};

export type Externals = {
  tvrage: number | null;
  thetvdb: number | null;
  imdb: null | string;
};

export type Image = {
  medium: string;
  original: string;
};

export enum Language {
  Chinese = 'Chinese',
  English = 'English',
  Japanese = 'Japanese'
}

export type Network = {
  id: number;
  name: string;
  country: Country;
  officialSite: null | string;
};

export type Country = {
  name: string;
  code: string;
  timezone: string;
};

export type Rating = {
  average: number | null;
};

export type Schedule = {
  time: string;
  days: string[];
};

export enum Status {
  Ended = 'Ended',
  Running = 'Running'
}

export enum Type {
  Animation = 'Animation',
  GameShow = 'Game Show',
  Scripted = 'Scripted'
}
